pipeline {
    agent any

    stages {
        stage('Doing things') {
            steps {
              echo "Here we're doing things"
            }
        }
        stage('End') {
            steps {
                echo "And we're done"
            }
        }
    }    
}